name: cybergame
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.6
  flutter_awesome_bottom_sheet: ^0.0.2
  awesome_dialog: ^3.2.1
  guarded_button: ^0.1.2
  video_player: ^2.9.1
  cached_network_image: ^3.4.0
  audioplayers: ^6.1.0
  just_audio: ^0.9.40
  flutter_screenutil: ^5.9.3
  http: ^1.2.2
  flame: 1.19.0
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  chewie: ^1.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/10back.png
    - assets/11back.png
    - assets/14back.png
    - assets/15back.png
    - assets/16back.png
    - assets/17back.png
    - assets/18back.png
    - assets/19back.png
    - assets/20back.png
    - assets/21back.png
    - assets/22back.png
    - assets/23back.png
    - assets/24back.png
    - assets/25back.png
    - assets/AntiGameBack.png
    - assets/antivirus_icon.png
    - assets/back.png
    - assets/BackGround1.png
    - assets/batoolChat.png
    - assets/blueBasket.png
    - assets/Botnet.png
    - assets/Box.png
    - assets/car.mp4
    - assets/carback.png
    - assets/carsong.mp3
    - assets/casel.png
    - assets/caselSong.mp3
    - assets/child_file.png
    - assets/child_file_infected.png
    - assets/child_file_safe.png
    - assets/click.mp3
    - assets/Clouds.png
    - assets/Computer1.png
    - assets/Computer2.png
    - assets/Computer3.png
    - assets/correct.mp3
    - assets/Cryptographygame.png
    - assets/CyberAttackPart.png
    - assets/Danger.png
    - assets/desktop1.png
    - assets/desktop2.png
    - assets/door1-highlight.mp4
    - assets/door1.mp4
    - assets/door2-highlight.mp4
    - assets/door2.mp4
    - assets/door3.mp4
    - assets/doorback.png
    - assets/doors.png
    - assets/DoorsVideo.mp4
    - assets/DownChar.png
    - assets/DownloaderV.png
    - assets/eightback.png
    - assets/error.mp3
    - assets/ether.png
    - assets/Evil.mp3
    - assets/Evil_laugh.mp3
    - assets/fiber.png
    - assets/filenames.txt
    - assets/fiveback.png
    - assets/GalaxyBack.mp4
    - assets/GalaxySong.mp3
    - assets/hanenChat.png
    - assets/HourseL1.png
    - assets/HttpMusic.mp3
    - assets/HttpsStop.gif
    - assets/HttpStop.gif
    - assets/InfectionV.png
    - assets/instalogo.png
    - assets/LeftChar.png
    - assets/LeftMaha.png
    - assets/linkback.png
    - assets/linksBack.gif
    - assets/LinkSong.mp3
    - assets/Lock.png
    - assets/loss.mp3
    - assets/MahaTalking.gif
    - assets/malicious_link.png
    - assets/MarioBackground.mp4
    - assets/mesage.png
    - assets/MobileSecurityPart.png
    - assets/modem.png
    - assets/MoveChar.webm
    - assets/NetworkBack.png
    - assets/NetworkBackground.png
    - assets/networkbuild.mp3
    - assets/netWorkPart.png
    - assets/network_cable.png
    - assets/nineback.png
    - assets/PartsPage.png
    - assets/phishing_email.png
    - assets/PassVideo.mp4
    - assets/phone.png
    - assets/pom.mp3
    - assets/portBack.png
    - assets/ports.png
    - assets/Printer.png
    - assets/put.mp3
    - assets/question_background.png
    - assets/Ransom.png
    - assets/RansomV.png
    - assets/redBasket.png
    - assets/RightChar.png
    - assets/RightMaha.png
    - assets/RO.png
    - assets/Router.mp3
    - assets/router.png
    - assets/RouterNew.png
    - assets/ROVID.gif
    - assets/secure.mp3
    - assets/sessionLayer.mp4
    - assets/sixback.png
    - assets/Soundgunshots.mp3
    - assets/SpaceBack.png
    - assets/SpaceCraft.png
    - assets/Spyware.png
    - assets/Stand.png
    - assets/StaticLeftChar.png
    - assets/StaticRightChar.png
    - assets/Stop.mp3
    - assets/Street.mp4
    - assets/Street1.png
    - assets/SW.png
    - assets/Switch.mp3
    - assets/switch.png
    - assets/SwitchNew.png
    - assets/SWVID.gif
    - assets/Tab.png
    - assets/the_char.mp3
    - assets/the_char.mp4
    - assets/TimeBumb.png
    - assets/TopChar.png
    - assets/transfer_arrow.png
    - assets/TroBack.png
    - assets/TrojanH.png
    - assets/trojenHorse.png
    - assets/tunnel.png
    - assets/UnderGround1.png
    - assets/UnderGround2.png
    - assets/victory.mp3
    - assets/viros.png
    - assets/Walking.mp3
    - assets/webSecurityPart.png
    - assets/wifi_spread.png
    - assets/WinBack.png
    - assets/Winning.mp3
    - assets/Worm.png
